[package]
name = "wait-online"
version = "0.1.0"
edition = "2018"
resolver = "2"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1"
backoff = { version = "0.3", features = ["tokio"] }
futures = "0.3"
once_cell = "1"
reqwest = "0.11"
tokio = { version = "1", features = ["rt", "macros"] }
